from invertedai_drive.drive import run


def test_mock():
    result = run(api_key='', model_key='', location='Town03_Roundabout',
                 x=[
                         [
                                 [
                                         0
                                 ]
                         ]
                 ],
                 y=[
                         [
                                 [
                                         0
                                 ]
                         ]
                 ],
                 psi=[
                         [
                                 [
                                         0
                                 ]
                         ]
                 ],
                 speed=[
                         [
                                 [
                                         0
                                 ]
                         ]
                 ],
                 length=[
                         [
                                 0
                         ]
                 ],
                 width=[
                         [
                                 0
                         ]
                 ],
                 lr=[
                         [
                                 0
                         ]
                 ],
                 recurrent_states=None,
                 present_masks=[
                         [
                                 [
                                         True
                                 ]
                         ]
                 ],
                 batch_size=1,
                 agent_counts=1,
                 obs_length=1,
                 step_times=1,
                 num_predictions=1)
    print(result)
