"""
Script to refilter t2f (third-person to first-person) scenarios from an existing log file.

This script loads a log file generated by waypoint_example_log_filter_t2f.py,
runs the t2f scenario detection again with configurable parameters,
and saves a new log file with updated t2f_scenarios.

Usage:
    python refilter_t2f_from_log.py <input_log.json> [--output <output_log.json>] [options]
"""

import invertedai as iai
from invertedai.logs.logger import LogReader
import json
import math
import os
import argparse
from typing import List, Tuple, Dict

# Import all the detection functions from the original script
def line_segment_intersects_rectangle(
    p1_x: float, p1_y: float,
    p2_x: float, p2_y: float,
    rect_center_x: float, rect_center_y: float,
    rect_length: float, rect_width: float,
    rect_orientation: float
) -> bool:
    """
    Check if a line segment intersects with a rotated rectangle (agent bounding box).
    
    Args:
        p1_x, p1_y: Start point of line segment
        p2_x, p2_y: End point of line segment
        rect_center_x, rect_center_y: Center of rectangle
        rect_length: Length of rectangle (along orientation)
        rect_width: Width of rectangle (perpendicular to orientation)
        rect_orientation: Orientation of rectangle in radians
    
    Returns:
        True if line segment intersects the rectangle, False otherwise
    """
    # Transform line segment to rectangle's local coordinate system
    cos_psi = math.cos(-rect_orientation)
    sin_psi = math.sin(-rect_orientation)
    
    # Translate to rectangle center
    p1_local_x = (p1_x - rect_center_x) * cos_psi - (p1_y - rect_center_y) * sin_psi
    p1_local_y = (p1_x - rect_center_x) * sin_psi + (p1_y - rect_center_y) * cos_psi
    p2_local_x = (p2_x - rect_center_x) * cos_psi - (p2_y - rect_center_y) * sin_psi
    p2_local_y = (p2_x - rect_center_x) * sin_psi + (p2_y - rect_center_y) * cos_psi
    
    # Rectangle bounds in local coordinates (axis-aligned)
    half_length = rect_length / 2.0
    half_width = rect_width / 2.0
    
    # Check if line segment intersects axis-aligned rectangle using Liang-Barsky algorithm
    dx = p2_local_x - p1_local_x
    dy = p2_local_y - p1_local_y
    
    # If line segment is a point
    if abs(dx) < 1e-9 and abs(dy) < 1e-9:
        return (-half_length <= p1_local_x <= half_length and 
                -half_width <= p1_local_y <= half_width)
    
    # Liang-Barsky line clipping algorithm
    t0, t1 = 0.0, 1.0
    
    for edge in range(4):
        if edge == 0:  # Left edge
            p, q = -dx, p1_local_x + half_length
        elif edge == 1:  # Right edge
            p, q = dx, half_length - p1_local_x
        elif edge == 2:  # Bottom edge
            p, q = -dy, p1_local_y + half_width
        else:  # Top edge
            p, q = dy, half_width - p1_local_y
        
        if abs(p) < 1e-9:  # Line is parallel to this edge
            if q < 0:
                return False
        else:
            r = q / p
            if p < 0:
                if r > t1:
                    return False
                elif r > t0:
                    t0 = r
            else:
                if r < t0:
                    return False
                elif r < t1:
                    t1 = r
    
    return t0 <= t1


def is_agent_in_fov(
    agent_a_state,
    agent_b_state,
    all_agent_states: List = None,
    all_agent_properties: List = None,
    agent_a_id: int = None,
    agent_b_id: int = None,
    fov_angle: float = 120.0,
    fov_range: float = 50.0
) -> bool:
    """
    Check if agent B is within agent A's field of view, considering line-of-sight blocking.
    
    Args:
        agent_a_state: AgentState of agent A (the observer)
        agent_b_state: AgentState of agent B (the target)
        all_agent_states: List of all agent states (for line-of-sight checking)
        all_agent_properties: List of all agent properties (for bounding box calculation)
        agent_a_id: ID of agent A (to exclude from blocking check)
        agent_b_id: ID of agent B (to exclude from blocking check)
        fov_angle: Field of view angle in degrees (default 120)
        fov_range: Field of view range in meters (default 50)
    
    Returns:
        True if agent B is within agent A's FoV and not blocked, False otherwise
    """
    # Calculate distance between agents
    dx = agent_b_state.center.x - agent_a_state.center.x
    dy = agent_b_state.center.y - agent_a_state.center.y
    distance = math.sqrt(dx**2 + dy**2)
    
    # Check if within range
    if distance > fov_range:
        return False
    
    # Calculate angle from agent A to agent B
    angle_to_b = math.atan2(dy, dx)
    
    # Normalize angles to [0, 2*pi]
    agent_a_orientation = agent_a_state.orientation % (2 * math.pi)
    angle_to_b = angle_to_b % (2 * math.pi)
    
    # Calculate angular difference
    angle_diff = abs(angle_to_b - agent_a_orientation)
    if angle_diff > math.pi:
        angle_diff = 2 * math.pi - angle_diff
    
    # Check if within FoV angle (half angle on each side)
    fov_half_angle_rad = (fov_angle / 2.0) * math.pi / 180.0
    
    if angle_diff > fov_half_angle_rad:
        return False
    
    # Check line-of-sight: see if any other agent blocks the view
    if all_agent_states is not None and all_agent_properties is not None:
        p1_x, p1_y = agent_a_state.center.x, agent_a_state.center.y
        p2_x, p2_y = agent_b_state.center.x, agent_b_state.center.y
        
        for agent_id, (other_state, other_props) in enumerate(zip(all_agent_states, all_agent_properties)):
            # Skip agent A and agent B
            if agent_id == agent_a_id or agent_id == agent_b_id:
                continue
            
            # Get agent dimensions
            length = other_props.length if other_props.length is not None else 5.0
            width = other_props.width if other_props.width is not None else 2.0
            if other_props.agent_type == "pedestrian":
                length = width = 1.5
            
            # Check if line segment from A to B intersects this agent's bounding box
            if line_segment_intersects_rectangle(
                p1_x, p1_y, p2_x, p2_y,
                other_state.center.x, other_state.center.y,
                length, width,
                other_state.orientation
            ):
                return False  # Blocked by this agent
    
    return True


def find_visibility_windows(
    drive_responses: List,
    agent_a_id: int,
    agent_b_id: int,
    all_agent_properties: List = None,
    fov_angle: float = 120.0,
    fov_range: float = 50.0,
    min_window_length: int = 40
) -> List[Tuple[int, int]]:
    """
    Find continuous time windows where agent A can see agent B.
    
    Returns:
        List of (start_timestep, end_timestep) tuples for valid windows
    """
    visibility = []
    
    for timestep, response in enumerate(drive_responses):
        # Check if both agents are present at this timestep
        if agent_a_id >= len(response.agent_states) or agent_b_id >= len(response.agent_states):
            visibility.append(False)
            continue
        
        agent_a_state = response.agent_states[agent_a_id]
        agent_b_state = response.agent_states[agent_b_id]
        
        # Skip if either agent is missing (None)
        if agent_a_state is None or agent_b_state is None:
            visibility.append(False)
            continue
        
        # Use provided agent properties (they should be static across timesteps)
        agent_props = all_agent_properties
        
        is_visible = is_agent_in_fov(
            agent_a_state, 
            agent_b_state,
            all_agent_states=response.agent_states,
            all_agent_properties=agent_props,
            agent_a_id=agent_a_id,
            agent_b_id=agent_b_id,
            fov_angle=fov_angle,
            fov_range=fov_range
        )
        visibility.append(is_visible)
    
    # Find continuous windows
    windows = []
    window_start = None
    
    for i, is_visible in enumerate(visibility):
        if is_visible and window_start is None:
            window_start = i
        elif not is_visible and window_start is not None:
            window_length = i - window_start
            if window_length >= min_window_length:
                windows.append((window_start, i - 1))
            window_start = None
    
    # Handle case where window extends to end
    if window_start is not None:
        window_length = len(visibility) - window_start
        if window_length >= min_window_length:
            windows.append((window_start, len(visibility) - 1))
    
    return windows


def find_nearby_agents(
    drive_responses: List,
    agent_a_id: int,
    agent_b_id: int,
    timestep: int,
    max_agents: int = 3,
    max_distance: float = None
) -> List[int]:
    """
    Find nearby agents to agent A at a given timestep.
    Agent B must be included. Returns up to max_agents agents.
    
    Args:
        max_distance: Maximum distance in meters. If None, no distance limit is applied.
    """
    if timestep >= len(drive_responses):
        return [agent_b_id]
    
    response = drive_responses[timestep]
    if agent_a_id >= len(response.agent_states) or agent_b_id >= len(response.agent_states):
        return [agent_b_id]
    
    agent_a_state = response.agent_states[agent_a_id]
    if agent_a_state is None:
        return [agent_b_id]
    
    # Calculate distances to all agents
    distances = []
    for agent_id, agent_state in enumerate(response.agent_states):
        if agent_id == agent_a_id or agent_state is None:
            continue
        
        dx = agent_state.center.x - agent_a_state.center.x
        dy = agent_state.center.y - agent_a_state.center.y
        distance = math.sqrt(dx**2 + dy**2)
        
        # Filter by max_distance if specified
        if max_distance is None or distance <= max_distance:
            distances.append((agent_id, distance))
    
    # Sort by distance
    distances.sort(key=lambda x: x[1])
    
    # Start with agent B (must be included, even if it exceeds max_distance)
    nearby = [agent_b_id]
    
    # Add other nearby agents (excluding A and B)
    for agent_id, _ in distances:
        if agent_id != agent_b_id and len(nearby) < max_agents:
            nearby.append(agent_id)
    
    return nearby


def has_stall_period(
    drive_responses: List,
    agent_id: int,
    windows: List[Tuple[int, int]],
    stall_threshold_speed: float = 0.1,
    min_stall_duration: int = 20
) -> bool:
    """
    Check if an agent has a stalling period (low/zero speed) of at least min_stall_duration timesteps
    within any of the given visibility windows.
    
    Args:
        drive_responses: List of drive responses for all timesteps
        agent_id: ID of the agent to check
        windows: List of (start, end) timestep tuples for visibility windows
        stall_threshold_speed: Speed threshold in m/s below which agent is considered stalling (default 0.1)
        min_stall_duration: Minimum consecutive timesteps of stalling to be considered a stall period (default 20)
    
    Returns:
        True if agent has a stall period of min_stall_duration or more timesteps, False otherwise
    """
    for window_start, window_end in windows:
        # Check for stalling within this window
        stall_start = None
        
        for timestep in range(window_start, window_end + 1):
            if timestep >= len(drive_responses):
                break
            
            response = drive_responses[timestep]
            if agent_id >= len(response.agent_states):
                continue
            
            agent_state = response.agent_states[agent_id]
            if agent_state is None:
                continue
            
            speed = abs(agent_state.speed)  # Use absolute speed
            
            if speed < stall_threshold_speed:
                # Agent is stalling
                if stall_start is None:
                    stall_start = timestep
            else:
                # Agent is moving
                if stall_start is not None:
                    stall_duration = timestep - stall_start
                    if stall_duration >= min_stall_duration:
                        return True  # Found a stall period of sufficient duration
                    stall_start = None
        
        # Check if stall period extends to end of window
        if stall_start is not None:
            stall_duration = (window_end + 1) - stall_start
            if stall_duration >= min_stall_duration:
                return True
    
    return False


def detect_t2f_scenarios(
    drive_responses: List,
    num_agents: int,
    all_agent_properties: List = None,
    fov_angle: float = 120.0,
    fov_range: float = 50.0,
    min_window_length: int = 40,
    filter_stalling: bool = True,
    min_stall_duration: int = 20,
    max_agents: int = 3
) -> List[Dict]:
    """
    Detect track-to-follow (t2f) scenarios from drive responses.
    
    Returns:
        List of scenario dictionaries with camera_mount_ids, replay_agent_ids, and valid_windows
    """
    scenarios = []
    
    # Check all pairs of agents
    for agent_a_id in range(num_agents):
        for agent_b_id in range(num_agents):
            if agent_a_id == agent_b_id:
                continue
            
            # Find visibility windows
            windows = find_visibility_windows(
                drive_responses,
                agent_a_id,
                agent_b_id,
                all_agent_properties=all_agent_properties,
                fov_angle=fov_angle,
                fov_range=fov_range,
                min_window_length=min_window_length
            )
            
            if windows:
                # Filter out scenarios where Agent B is stalling for 20+ timesteps
                if filter_stalling and has_stall_period(drive_responses, agent_b_id, windows, min_stall_duration=min_stall_duration):
                    continue  # Skip this scenario
                
                # Use the first window to determine nearby agents
                first_window_start = windows[0][0]
                max_distance = 2.0 * fov_range  # 2x FoV range
                replay_agent_ids = find_nearby_agents(
                    drive_responses,
                    agent_a_id,
                    agent_b_id,
                    first_window_start,
                    max_distance=max_distance,
                    max_agents=max_agents
                )
                
                scenario = {
                    "camera_mount_ids": [agent_a_id, agent_b_id],
                    "observer_id": agent_a_id,  # Agent A is the camera being used
                    "instance_mask_id": agent_b_id,  # Agent B is the target being observed
                    "replay_agent_ids": replay_agent_ids+[agent_a_id],
                    "valid_windows": [[start, end] for start, end in windows]
                }
                scenarios.append(scenario)
    
    return scenarios


class MockDriveResponse:
    """Simple mock class to mimic DriveResponse for detection functions."""
    def __init__(self, agent_states):
        self.agent_states = agent_states


def main():
    parser = argparse.ArgumentParser(description='Refilter t2f scenarios from a log file')
    parser.add_argument('input_log', type=str, help='Path to input log JSON file')
    parser.add_argument('--output', type=str, default=None, help='Path to output log JSON file (default: adds _refiltered suffix)')
    parser.add_argument('--output-dir', type=str, default=None, help='Directory to save output file (default: same as input file)')
    parser.add_argument('--fov-angle', type=float, default=110.0, help='Field of view angle in degrees (default: 120.0)')
    parser.add_argument('--fov-range', type=float, default=20.0, help='Field of view range in meters (default: 25.0)')
    parser.add_argument('--min-window-length', type=int, default=30, help='Minimum window length in timesteps (default: 30)')
    parser.add_argument('--filter-stalling', action='store_true', default=True, help='Filter out scenarios with stalling agents (default: True)')
    parser.add_argument('--no-filter-stalling', dest='filter_stalling', action='store_false', help='Do not filter out scenarios with stalling agents')
    parser.add_argument('--min-stall-duration', type=int, default=10, help='Minimum stall duration in timesteps (default: 10)')
    parser.add_argument('--max-agents', type=int, default=4, help='Maximum number of agents to consider for nearby agents (default: 3)')
    args = parser.parse_args()
    
    # Load the log file
    print(f"Loading log file: {args.input_log}")
    log_reader = LogReader(args.input_log)
    
    # Get agent states and properties from the log
    all_agent_states = log_reader._scenario_log.agent_states
    all_agent_properties = log_reader._scenario_log.agent_properties
    present_indexes = log_reader._scenario_log.present_indexes
    
    # Determine number of agents
    num_agents = len(all_agent_properties)
    print(f"Found {num_agents} agents in log file")
    print(f"Simulation length: {len(all_agent_states)} timesteps")
    
    # Create mock DriveResponse objects for each timestep
    # Note: timestep 0 is from initialize, so we skip it and start from timestep 1
    # We need to handle cases where agents may not be present at all timesteps
    # by creating a full list with None for missing agents
    drive_responses = []
    for timestep in range(1, len(all_agent_states)):
        agent_states_ts = all_agent_states[timestep]
        
        if present_indexes is not None:
            present_ids_ts = present_indexes[timestep]
            # Create a full list indexed by agent_id, with None for missing agents
            full_agent_states = [None] * num_agents
            # agent_states_ts is already sorted by present_ids_ts order
            for idx, agent_id in enumerate(present_ids_ts):
                if agent_id < num_agents and idx < len(agent_states_ts):
                    full_agent_states[agent_id] = agent_states_ts[idx]
        else:
            # All agents are present, use agent_states_ts directly
            full_agent_states = agent_states_ts
        
        drive_responses.append(MockDriveResponse(full_agent_states))
    
    print(f"Created {len(drive_responses)} drive responses")
    
    # Detect t2f scenarios
    print("Detecting t2f scenarios...")
    print(f"  FoV angle: {args.fov_angle} degrees")
    print(f"  FoV range: {args.fov_range} meters")
    print(f"  Min window length: {args.min_window_length} timesteps")
    print(f"  Filter stalling: {args.filter_stalling}")
    if args.filter_stalling:
        print(f"  Min stall duration: {args.min_stall_duration} timesteps")
    
    t2f_scenarios = detect_t2f_scenarios(
        drive_responses=drive_responses,
        num_agents=num_agents,
        all_agent_properties=all_agent_properties,
        fov_angle=args.fov_angle,
        fov_range=args.fov_range,
        min_window_length=args.min_window_length,
        filter_stalling=args.filter_stalling,
        min_stall_duration=args.min_stall_duration,
        max_agents=args.max_agents
    )
    
    print(f"Found {len(t2f_scenarios)} t2f scenarios")
    
    # Load the original log file as JSON
    with open(args.input_log, 'r') as f:
        log_data = json.load(f)
    
    # Show comparison with original scenarios if they exist
    original_count = len(log_data.get('t2f_scenarios', []))
    if original_count > 0:
        print(f"Original log had {original_count} t2f scenarios")
        print(f"New log will have {len(t2f_scenarios)} t2f scenarios")
    
    # Update t2f_scenarios in the log data
    log_data['t2f_scenarios'] = t2f_scenarios
    
    # Determine output path
    if args.output is None:
        # Generate filename based on input filename
        input_basename = os.path.basename(args.input_log)
        input_name, input_ext = os.path.splitext(input_basename)
        # add fov-angle and fov-range to the output filename
        output_filename = f"{input_name}_refiltered_fov{args.fov_angle}_range{args.fov_range}.json"
        
        # Use output directory if specified, otherwise use input file's directory
        if args.output_dir is not None:
            output_path = os.path.join(args.output_dir, output_filename)
        else:
            # Use same directory as input file
            input_dir = os.path.dirname(args.input_log)
            output_path = os.path.join(input_dir, output_filename) if input_dir else output_filename
    else:
        # If --output is specified, use it directly (takes precedence over --output-dir)
        output_path = args.output
    
    # Create output directory if needed
    output_dir = os.path.dirname(output_path)
    if output_dir and not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    # Save the updated log file
    print(f"Saving updated log file to: {output_path}")
    with open(output_path, 'w') as f:
        json.dump(log_data, f, indent=4)
    
    print(f"Done! Output saved to {os.path.abspath(output_path)}")


if __name__ == "__main__":
    main()

